### ISSUE TITLE
github dependabot alerts

### ISSUE THREAD

**Issue by amosmos** [laravel/nova-js#59]
Hi,

We got a lot of dependabot critical and high alerts complaining about different packages found in yarn.lock file.
We are using nova v3, and thought that perhaps upgrading to the latest release (3.32) will solve this, but actually now we have doubled the alerts.

What we don't understand is if these packages are even installed on our application.
We follow the nova installation guide (v3) and nowhere did it mention we need to install any npm\yarn packages.
We also checked the artisan nova:install and aritsan nova:publish commands and didn't see it install any npm\yarn packages.
We also didn't find any node_modules folder in our project.

So we assume we never actually installed any npm\yarn packages, so we assume we can ignore dependabot alerts.
Can you advise?

Also - if indeed we never actually installed the npm packages - why is there a yarn.lock file? What is it used for?

Thanks!
Amos

**Comment by driesvints** [comment]
Please report this to https://github.com/laravel/nova-issues/issues
